fix in to_interchange_format
pik-primap/primap2 pull request #122
Opened 2022-08-23 07:47 UTC by JGuetschow

# Pull request

Please confirm that this pull request has done the following:

- [ ] Tests added
- [x] Documentation added (where applicable)
- [x] Description in a ``.rst`` file in the directory ``changelog_unreleased`` added - remember to include a ``*`` to make it a bullet point
No new functionality added, tests  are not affected. One could add a tests for the bug that has been fixed.

## Description

Fix in to_interchnage_format. Before timeseries which contained only nan were kept (I assume the intention was to remove them, as there was a dropna in the code). On the other hand time series which contained only a few (or single) data points were in some cases dropped. This has now been fixed by specifying the time columns as subset in dropna.

A further tiny fix is to make regexp_unit optional in nir_add_unit_information as was intended already before, but not indicated in the function header.

2022-09-12 15:18 UTC, mikapfl requested changes
Thanks for finding the problem + fixing it. I'd appreciate a test, since I don't fully understand what is going on and why `how = "all"` doesn't do what I thought it would. With a test case, we could make sure we're not getting regressions later on. But it might be difficult to engineer a nice test case.

Other changes that I requested are just typos I think and an inadvertently included unrelated change.

2022-09-12 15:18 UTC, mikapfl commented on changelog_unreleased/fix-data-reading.rst
> +* Fix handling of units when reading data where CO2eq and native units coexist
? I don't see any changes in the code related to this.

2022-09-12 15:18 UTC, mikapfl commented on primap2/_merge.py
> +    error_on_discrepancy (optional), default = True
```suggestion
    error_on_discrepancy: (optional), default = True
```
Why remove the `:`?

2022-09-12 15:18 UTC, mikapfl commented on primap2/_merge.py
> +        error_on_discrepancy (optional), default = True
```suggestion
        error_on_discrepancy: (optional), default = True
```

2022-09-13 12:38 UTC, JGuetschow commented
I will add a test. I was also puzzled that "all" didn't do what it supposedly should. Maybe it's a bug. When we have a minimal test we can investigate further.

2022-11-01 08:29 UTC, mikapfl commented
I think we can merge the fix also without the minimal test case. Better have the fix without a test than to have an unfixed primap.

2022-11-02 12:15 UTC, JGuetschow commented
I think my description is wrong. Only one of the two issues was present, namely keeping the all-nan timeseries. The dropping of singe data points was a mistake by me, I think. Thus I think merging is fine without a test, because the fixed issue is actually small. The larger issue did not exist in the first place, I think.

2022-11-02 13:30 UTC, merged